
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzanuwnfcbmdfbstgggy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6YW51d25mY2JtZGZic3RnZ2d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzIyMDQsImV4cCI6MjA3NDIwODIwNH0.mp1Uh1gw6JIVdvmRUqxgoMWP9VUYbGw0F5ScMKHnBvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
